# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pyxiong/FIFO_Cascading/FIFO_Cascading.cache/wt [current_project]
set_property parent.project_path /home/pyxiong/FIFO_Cascading/FIFO_Cascading.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/pyxiong/FIFO_Cascading/FIFO_Cascading.runs/fifo_standard_synth_1/fifo_standard.dcp
set_property used_in_implementation false [get_files /home/pyxiong/FIFO_Cascading/FIFO_Cascading.runs/fifo_standard_synth_1/fifo_standard.dcp]
add_files -quiet /home/pyxiong/FIFO_Cascading/FIFO_Cascading.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp
set_property used_in_implementation false [get_files /home/pyxiong/FIFO_Cascading/FIFO_Cascading.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp]
read_verilog -library xil_defaultlib /home/pyxiong/FIFO_Cascading/FIFO_Cascading.srcs/sources_1/new/fifo_cascading.v
synth_design -top fifo_cascading -part xcku040-ffva1156-2-e
write_checkpoint -noxdef fifo_cascading.dcp
catch { report_utilization -file fifo_cascading_utilization_synth.rpt -pb fifo_cascading_utilization_synth.pb }
